<footer class="bg-primary">
    <div class="container-fluid py-3">
        <div class="container">
        <div class="row">
            <div class="col-md-3">
                <h5>Contact Information</h5></div>
            <div class="col-md-3"></div>
            <div class="col-md-3"></div>
            <div class="col-md-3"></div>
        </div>
        <div class="row">
            <div class="col-md-6">70 The Pond Rd, North York,<br/>Ontario, Canada, M3J 3M6</div>
            <div class="col-md-3"></div>
            <div class="col-md-3 text-right small align-self-end">Wecreu &copy;<?php echo date("Y"); ?></div>
        </div>
        </div>
    </div>
</footer>